revision = '2a3ecef7ee4d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist', 'title', name=u'ix_track_artist_title')
    )
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('html', sa.UnicodeText(), nullable=True),
    sa.Column('provider', sa.Unicode(length=255), nullable=True),
    sa.Column('artist', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist', 'title', name=u'ix_lyrics_artist_title')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Binary(), nullable=False),
    sa.Column('checksum', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], [u'track.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', name=u'ix_file_path')
    )
    op.create_index('ix_file_checksum', 'file', ['checksum'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_checksum', table_name='file')
    op.drop_table('file')
    op.drop_table('lyrics')
    op.drop_table('track')
    ### end Alembic commands ###
